# Cecaj sleep fitbit data score
* calculated sleep score and label the datas



### Sleep score
based on Dr. Oz
http://blog.doctoroz.com/oz-experts/calculating-your-perfect-bedtime-and-sleep-efficiency

NOTE: number of awakenings are not included in the score


The labels for the sleep quality are also based on Dr. Oz classification.
* <= 75% bad sleep -> own classification -> 3
*  \> 75% sufficient sleep -> own classification -> 2
*  \> 85% normal sleep -> 1
*  \> 90% good sleep -> 0

In [41]:
######### config section #########
activity_data_file = "OneYearFitBitDataEdited.csv"
sleep_data_file = "OneYearFitBitDataSleep.csv"
sleep_data_score_output_file = 'OneYearFitBitDataSleepScore.csv'

In [42]:
import pandas as pd
from IPython.display import display, HTML

In [43]:
def main():
    sleep_data = pd.read_csv(sleep_data_file, sep = ',')
    sleep_score_df = calc_sleep_score(sleep_data)
    sleep_score_df = create_sleep_score_label(sleep_score_df)
    display(sleep_score_df)
    sleep_score_df.to_csv(sleep_data_score_output_file, index=False)
    
    return

In [44]:
def calc_sleep_score(sleep_data):
    
    sleep_data_col = (sleep_data['MinutesOfSleep'] - sleep_data['MinutesOfBeingAwake'])/ \
                      sleep_data['LengthOfRestInMinutes']
    
    sleep_score_df = pd.concat([sleep_data, sleep_data_col], axis=1)
    sleep_score_df = sleep_score_df.rename(columns = {0: 'SleepScore'}) # adds column header
    
    return sleep_score_df

In [45]:
def create_sleep_score_label(sleep_score_df):
    sleep_scores = sleep_score_df['SleepScore']
    sleep_labels = pd.DataFrame(columns=['sleep_labels'])

    for score in sleep_scores:
        if score > 0.9:
            sleep_labels = sleep_labels.append(pd.Series(['0'],index = ['sleep_labels']), ignore_index=True)
        elif score > 0.85:
            sleep_labels = sleep_labels.append(pd.Series(['1'],index = ['sleep_labels']), ignore_index=True)
        elif score > 0.75:
            sleep_labels = sleep_labels.append(pd.Series(['2'],index = ['sleep_labels']), ignore_index=True)
        elif score <= 0.75:
            sleep_labels = sleep_labels.append(pd.Series(['3'],index = ['sleep_labels']), ignore_index=True)
        else:
            sleep_labels = sleep_labels.append(pd.Series(['NaN'],index = ['sleep_labels']), ignore_index=True)
            
            
    sleep_score_df = pd.concat([sleep_score_df, sleep_labels], axis=1)   
    
    
    return sleep_score_df

In [46]:
if __name__ == '__main__':
    main()

,Date,MinutesOfSleep,MinutesOfBeingAwake,NumberOfAwakings,LengthOfRestInMinutes,SleepScore,sleep_labels
0,09-05-2015,384,26,23,417,0.858513,1
1,10-05-2015,454,35,21,491,0.853360,1
2,11-05-2015,387,46,25,436,0.782110,2
3,12-05-2015,311,31,21,350,0.800000,2
4,13-05-2015,407,65,44,491,0.696538,3
5,14-05-2015,405,47,31,457,0.783370,2
6,15-05-2015,381,28,12,415,0.850602,1
7,16-05-2015,269,34,16,306,0.767974,2
8,17-05-2015,452,26,18,507,0.840237,2
9,18-05-2015,269,17,11,291,0.865979,1
10,19-05-2015,167,9,8,180,0.877778,1
11,20-05-2015,368,50,27,420,0.757143,2
12,21-05-2015,386,30,22,420,0.847619,2
13,22-05-2015,351,46,26,399,0.764411,2
14,23-05-2015,314,32,26,353,0.798867,2
15,24-05-2015,432,35,24,469,0.846482,2
16,25-05-2015,224,24,19,270,0.740741,3
17,26-05-2015,0,0,0,0,NaN,NaN
18,27-05-2015,389,39,28,430,0.813953,2
19,28-05-2015,381,24,17,412,0.866505,1
20,29-05-2015,417,66,32,486,0.722222,3
21,30-05-2015,464,35,26,503,0.852883,1
22,31-05-2015,328,53,25,382,0.719895,3
23,01-06-2015,426,54,33,495,0.751515,2
24,02-06-2015,430,41,26,484,0.803719,2
25,03-06-2015,376,46,34,436,0.756881,2
26,04-06-2015,312,44,29,369,0.726287,3
27,05-06-2015,388,21,15,415,0.884337,1
28,06-06-2015,409,56,34,468,0.754274,2
29,01-06-2015,426,54,27,495,0.751515,2
...,...,...,...,...,...,...,...
337,08-04-2016,379,46,24,425,0.783529,2
338,09-04-2016,507,18,10,525,0.931429,0
339,10-04-2016,306,35,22,341,0.794721,2
340,11-04-2016,407,50,26,457,0.781182,2
341,12-04-2016,354,37,21,391,0.810742,2
342,13-04-2016,365,65,31,430,0.697674,3
343,14-04-2016,278,26,18,304,0.828947,2
344,15-04-2016,396,50,20,446,0.775785,2
345,16-04-2016,404,67,25,471,0.715499,3
346,17-04-2016,0,0,0,0,NaN,NaN
347,18-04-2016,307,28,12,335,0.832836,2
348,19-04-2016,0,0,0,0,NaN,NaN
349,20-04-2016,411,31,17,442,0.859729,1
350,21-04-2016,341,27,17,368,0.853261,1
351,22-04-2016,430,62,39,492,0.747967,3
352,23-04-2016,305,42,28,348,0.755747,2
353,24-04-2016,375,56,31,431,0.740139,3
354,25-04-2016,237,28,14,265,0.788679,2
355,26-04-2016,360,20,10,380,0.894737,1
356,27-04-2016,361,49,27,410,0.760976,2
357,28-04-2016,374,56,34,430,0.739535,3
358,29-04-2016,348,20,9,368,0.891304,1
359,30-04-2016,454,48,27,502,0.808765,2
360,01-05-2016,347,41,20,388,0.788660,2
361,02-05-2016,314,34,23,348,0.804598,2
362,03-05-2016,377,33,18,410,0.839024,2
363,04-05-2016,406,21,8,427,0.901639,0
364,05-05-2016,280,35,15,315,0.777778,2
365,06-05-2016,370,42,22,412,0.796117,2
366,07-05-2016,502,57,31,563,0.790409,2